

server:
  port: 8989
  servlet:
    context-path: /travel

spring:
  application:
    name: travels
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travels?characterEncoding=UTF-8
    username: root
    password: 123456
  web:
    resources:
      static-locations: classpath:/static/

mybatis:
  config-locations: classpath:com/yswu/travel/mapper/*.xml
  type-aliases-package: com.yswu.travel.entity
